server:
  host: "127.0.0.1"
  port: "8888"
  mode: "default"
postgres:
  host: "postgres"
  port: "5432"  
  name: "galanonim"
  user: "galanonimuser"
  password: "galanonimpassword"
jwt:
  tokenSecret: "someTokenSecretJWT"
  expTime: 1
  issuer: "galanonim"
redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0
filestorage:
  endpoint: ""
  accessKeyID: ""
  secretAccessKey: ""
  secure: TRUE
  maxUploadSize: 1000000000